version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ascension-rest-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-x2zew3a5x75o"
s3_prefix = "ascension-rest-api"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

